### General NumPy

In [1]:
import numpy as np


In [ ]:
### Arrays is Numpy
- Homogeneous has to  only contain 1 data type.
- all elements of array MUST be the same data type
- The shape  must be rectangular 

In [ ]:
# single dimensional array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
a[-1 : 0 : -1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [5]:
multiDimArr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(multiDimArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# ** difference  from lists**
# can access multi dimensions using ordered pair
multiDimArr[2, 2]

np.int64(11)

In [8]:
# to view data types of datasets
print('Data Type of array:', a.dtype)
print('Data Shape/Dimensions:', a.ndim)


Data Type of array: int64
Data Shape/Dimensions: 1


In [10]:
print('Data Type of array:', multiDimArr.dtype)
print('Data Shape/Dimensions:', multiDimArr.ndim)
rows, cols = multiDimArr.shape

print('Rows:', rows)
print('Cols:', cols)

Data Type of array: int64
Data Shape/Dimensions: 2
Rows: 3
Cols: 4


In [11]:
print(multiDimArr.shape)

(3, 4)


In [12]:
# arange to create quick numerical arrays (start, stop, step)
one_to_100 = np.arange(1, 100)

print(one_to_100)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
