### General NumPy

In [1]:
import numpy as np


In [ ]:
### Arrays is Numpy
- Homogeneous has to  only contain 1 data type.
- all elements of array MUST be the same data type
- The shape  must be rectangular 

In [ ]:
# single dimensional array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
a[-1 : 0 : -1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [5]:
multiDimArr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(multiDimArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# ** difference  from lists**
# can access multi dimensions using ordered pair
multiDimArr[2, 2]

np.int64(11)

In [8]:
# to view data types of datasets
print('Data Type of array:', a.dtype)
print('Data Shape/Dimensions:', a.ndim)


Data Type of array: int64
Data Shape/Dimensions: 1


In [10]:
print('Data Type of array:', multiDimArr.dtype)
print('Data Shape/Dimensions:', multiDimArr.ndim)
rows, cols = multiDimArr.shape

print('Rows:', rows)
print('Cols:', cols)

Data Type of array: int64
Data Shape/Dimensions: 2
Rows: 3
Cols: 4


In [11]:
print(multiDimArr.shape)

(3, 4)


In [12]:
# arange to create quick numerical arrays (start, stop, step)
one_to_100 = np.arange(1, 100)

print(one_to_100)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [13]:
# A range array range 
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# Arithmetic Operations Numpy
# Element-wise arithmatic (for each element)
sum_arr = arr + 10
print(sum_arr)

[11 12 13 14 15 16 17 18 19 20]


In [15]:
sub_arr = arr - 4
print(sub_arr)

[-3 -2 -1  0  1  2  3  4  5  6]


In [16]:
div_arr = arr / 2
print(div_arr)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [17]:
mult_arr = arr * 100
print(mult_arr)

[ 100  200  300  400  500  600  700  800  900 1000]


In [18]:
sum = np.sum(arr)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
standard_dev = np.std(arr)
min = np.min(arr)
max = np.max(arr)

print('Sum:', sum)
print('Mean:', mean)
print('Median:', median)
print(f'Standard dev: {standard_dev}')
print(f'Variance: {variance}')
print(f'Min: {min}')
print(f'Max: {max}')

Sum: 55
Mean: 5.5
Median: 5.5
Standard dev: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10


In [19]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [20]:
transposed_matrix = matrix.T
print(transposed_matrix)

[[1 4]
 [2 5]
 [3 6]]


In [21]:
reshaped_matrix = matrix.reshape(3, 2)
print(reshaped_matrix)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
# argmin(), arg(max) - index of min and max values
print(np.argmin(arr))
print(np.argmax(arr))

0
9


In [23]:
# argmin(), arg(max) - index of min and max values
print(np.argmin(arr))
print(np.argmax(arr))

0
9


In [24]:
fruitArr = np.array(['apple', 'banana', 'apple', 'apple', 'plum', 'mango', 'bnnana'])

print(np.unique(fruitArr))

['apple' 'banana' 'bnnana' 'mango' 'plum']


In [25]:
countries = np.array(['USA', 'United State', 'United State of America', 'France'])

np.unique(countries)

array(['France', 'USA', 'United State', 'United State of America'],
      dtype='<U23')

In [26]:
decade1 = np.arange(1980, 1990)
decade2 = np.arange(1990, 2000)
decade3 = np.arange(2000, 2010)

# print(decade1)
# print(decade2)
# print(decade3)

allYears = np.concat((decade1, decade2, decade3))

print(allYears)

[1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993
 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007
 2008 2009]
